version: '3'
volumes:
  redash-postgres-data:

x-redash-service: &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres
    - redis
  env_file: docker/env/.redash.env
  restart: always

networks:
  default:
    external:
      name: streamer_network

services:
  redash-init:
    build: redash_dashboard
    env_file: 
      - redash_dashboard/example.env
    depends_on: 
      - redash-server
    restart: "no"
  
  redash-server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
      - "5678:5678"

  redash-scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1

  redash-scheduled-worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  redash-adhoc-worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  postgres:
    image: postgres:13-alpine
    env_file: docker/env/.redash.env
    volumes:
      - redash-postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:5.0-alpine
    restart: always

  email:
    image: djfarrelly/maildev
    restart: unless-stopped
    ports:
      - "1080:80"
