---
apiVersion: v2
name: mbelt
description: Mbelt helm chart
version: 1.0.1
appVersion: 1.0.0
maintainers:
- name: Artem Nurmatov
  email: artem.n@p2p.org
dependencies:
  # installes rabbitmq vhost, users and permissions
  - name: rabbitmq-tenant
    repository: oci://europe-west4-docker.pkg.dev/iaas-383414/iaas/helm
    version: v0.3.1
    alias: rabbitmq
    condition: rabbitmq.enabled
