---
environment: stage
replicas: 1
name: block-processor
limits: {cpu: 250m, memory: 8000Mi}
requests: {cpu: 150m, memory: 8000Mi}
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: 663e9e079f4e38dd74f65f3f1de92ef8fe67b0ff}
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
additional_args:
  - "--max_old_space_size=8000"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: BLOCK_PROCESSOR
  network: polkadot
ingress:
  enabled: true
  class: nginx-external
  host: mbelt-stage-block-processor.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt-stage-block-processor-polka-p2p-world
    ssl_redirect: true
