---
environment: stage
name: preloader
replicas: 1
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: f4b1b716941af20b0ba830e0b504627eacaaa67a}
limits: {cpu: 450m, memory: 200Mi}
requests: {cpu: 400m, memory: 200Mi}
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: LISTENER
  network: polkadot
ingress:
  enabled: false
