---
environment: stage
name: staking-processor
replicas: 1
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: 6697d5ffc179f9456bd4c67dc6fb0b140fdea866}
limits: {cpu: 450m, memory: 512Mi}
requests: {cpu: 350m, memory: 512Mi}
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: STAKING_PROCESSOR
  network: polkadot
ingress:
  enabled: false
