---
environment: stage
replicas: 10
name: block-processor
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: 69f002d4b56b7df6594e18fb8d6a6ca5bc464829}
limits: {cpu: 450m, memory: 512Mi}
requests: {cpu: 350m, memory: 512Mi}
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: BLOCK_PROCESSOR
  network: polkadot
ingress:
  enabled: true
  class: nginx-external
  host: mbelt-stage-block-processor.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt-stage-block-processor-polka-p2p-world
    ssl_redirect: true
