---
environment: prod
name: kusama
image: {repository: eu.gcr.io/substrate-infra/mbelt2_streamer, tag: 56ea9631c3c5a770ca330631110c132beb02aeb7}
limits: {cpu: 1000m, memory: 2Gi}
requests: {cpu: 300m, memory: 2Gi}
port: 3000
metrics:
  enabled: true
vault:
  role: "mbelt"
  secret: "secret/mbelt/v2_prod"
env:
  substrate_uri: ws://kusama-node-0.kusama-node.kusama.svc.cluster.local:9944
  log_level: trace
  preload: true
  subscribe: true
  start_block_id: 0
  network: kusama
ingress:
  enabled: true
  class: nginx-external
  host: mbelt-kusama.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt-kusama-polka-p2p-world
    ssl_redirect: true
