---
environment: stage

vault: &vault
  role: "mbelt"
  secret: "secret/mbelt/stage"

streamers:
  preloader:
    name: preloader
    image: { repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: v1.0.5 }
    limits: { cpu: 1000m, memory: 2Gi }
    requests: { cpu: 300m, memory: 2Gi }
    port: 3000
    vault: *vault
    env:
      substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
      log_level: info
      network_id: 1
      mode: LISTENER
    ingress:
      enabled: false

  block-processor:
    name: block-processor
    image: { repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: v1.0.5 }
    limits: { cpu: 500m, memory: 500Mi }
    requests: { cpu: 300m, memory: 500Mi }
    port: 3000
    vault: *vault
    env:
      substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
      log_level: info
      network_id: 1
      mode: BLOCK_PROCESSOR
    ingress:
      enabled: false

  # - name: polkadot
  #   image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer, tag: v1.0.9 }
  #   limits: { cpu: 1000m, memory: 2Gi }
  #   requests: { cpu: 300m, memory: 2Gi }
  #   port: 3000
  #   env:
  #     substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  #     log_level: trace
  #     preload: true
  #     subscribe: true
  #     start_block_id: 0
  #     basic_auth: true
  #     rest_api_basic_auth_password: QF4cusBhLspZhwQe562c9vPR
  #   ingress:
  #     enabled: true
  #     class: nginx-external
  #     host: mbelt-stage-polkadot.polka.p2p.world
  #     tls:
  #       cluster_issuer: cloudflare-prod
  #       secret: mbelt-stage-polkadot-polka-p2p-world
  #       ssl_redirect: true
  #
  # - name: kusama
  #   image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer, tag: v1.0.9 }
  #   limits: { cpu: 1000m, memory: 2Gi }
  #   requests: { cpu: 300m, memory: 2Gi }
  #   port: 3000
  #   env:
  #     substrate_uri: ws://kusama-node-0.kusama-node.kusama.svc.cluster.local:9944
  #     log_level: trace
  #     preload: true
  #     subscribe: true
  #     start_block_id: 0
  #     basic_auth: true
  #     rest_api_basic_auth_password: cfWycZr8jb2HzWBrHp3zBMRy
  #   ingress:
  #     enabled: true
  #     class: nginx-external
  #     host: mbelt-stage-kusama.polka.p2p.world
  #     tls:
  #       cluster_issuer: cloudflare-prod
  #       secret: mbelt-stage-kusama-polka-p2p-world
  #       ssl_redirect: true
