---
environment: stage
replicas: 50
name: block-processor
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: 20370f2b1e9ff5c5db5716bcc8d7ef4bd22292aa}
limits: {cpu: 250m, memory: 2048Mi}
requests: {cpu: 150m, memory: 2048Mi}
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
additional_args:
  - "--max_old_space_size=2048"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: BLOCK_PROCESSOR
  network: polkadot
ingress:
  enabled: true
  class: nginx-external
  host: mbelt-stage-block-processor.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt-stage-block-processor-polka-p2p-world
    ssl_redirect: true
