---
environment: stage
replicas: 10
name: block-processor
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: bfdc644888d873365df7d6f25a6e06bb31264fc6}
limits: {cpu: 250m, memory: 200Mi}
requests: {cpu: 150m, memory: 200Mi}
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: BLOCK_PROCESSOR
  network: polkadot
ingress:
  enabled: false
