---
environment: stage
replicas: 50
name: block-processor
image:
  {
    repository: eu.gcr.io/substrate-infra/mbelt3_preloader,
    tag: 54926525ab7261ddaa3c1de642d05b84311291e7,
  }
limits: { cpu: 250m, memory: 200Mi }
requests: { cpu: 150m, memory: 200Mi }
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: BLOCK_PROCESSOR
  network: polkadot
ingress:
  enabled: false
