---
environment: prod

vault:
  role: "mbelt"
  secret: "secret/mbelt/v2_prod"

streamers:
  - name: polkadot
    image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer, tag: v1.0.9_main }
    limits: { cpu: 1000m, memory: 2Gi }
    requests: { cpu: 300m, memory: 2Gi }
    port: 3000
    db: *db
    env:
      substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
      log_level: trace
      preload: true
      subscribe: true
      start_block_id: 0
      basic_auth: true
    ingress:
      enabled: true
      class: nginx-external
      host: mbelt-polkadot.polka.p2p.world
      tls:
        cluster_issuer: cloudflare-prod
        secret: mbelt-polkadot-polka-p2p-world
        ssl_redirect: true

  - name: kusama
    image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer, tag: v1.0.9_main }
    limits: { cpu: 1000m, memory: 2Gi }
    requests: { cpu: 300m, memory: 2Gi }
    port: 3000
    db: *db
    env:
      substrate_uri: ws://kusama-node-0.kusama-node.kusama.svc.cluster.local:9944
      log_level: trace
      preload: true
      subscribe: true
      start_block_id: 0
      basic_auth: true
    ingress:
      enabled: true
      class: nginx-external
      host: mbelt-kusama.polka.p2p.world
      tls:
        cluster_issuer: cloudflare-prod
        secret: mbelt-kusama-polka-p2p-world
        ssl_redirect: true

  - name: moonriver
    image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer_moonbeam, tag: v1.0.10 }
    limits: { cpu: 700m, memory: 2Gi }
    requests: { cpu: 500m, memory: 2Gi }
    port: 3000
    db: *db
    env:
      substrate_uri: ws://moonriver-node-0.moonriver-node.moonriver.svc.cluster.local:9945
      log_level: warn
      preload: true
      subscribe: true
      start_block_id: 0
    ingress:
      enabled: true
      class: nginx-external
      host: mbelt-moonriver.polka.p2p.world
      tls:
        cluster_issuer: cloudflare-prod
        secret: mbelt-moonriver-polka-p2p-world
        ssl_redirect: true

  - name: moonbeam
    image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer_moonbeam, tag: v1.0.10 }
    limits: { cpu: 700m, memory: 2Gi }
    requests: { cpu: 500m, memory: 2Gi }
    port: 3000
    db: *db
    env:
      substrate_uri: ws://moonbeam-node-0.moonbeam-node.moonbeam.svc.cluster.local:9945
      log_level: warn
      preload: true
      subscribe: true
      start_block_id: 0
    ingress:
      enabled: true
      class: nginx-external
      host: mbelt-moonbeam.polka.p2p.world
      tls:
        cluster_issuer: cloudflare-prod
        secret: mbelt-moonbeam-polka-p2p-world
        ssl_redirect: true

  # - name: karura
  #   image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer_karura, tag: v1.0.0 }
  #   limits: { cpu: 700m, memory: 3Gi }
  #   requests: { cpu: 500m, memory: 3Gi }
  #   port: 3000
  #   db: *db
  #   env:
  #     substrate_uri: ws://karura-node-0.karura-node.karura.svc.cluster.local:9945
  #     log_level: warn
  #     preload: true
  #     subscribe: true
  #     start_block_id: 0
  #   ingress:
  #     enabled: true
  #     class: nginx-external
  #     host: mbelt-karura.polka.p2p.world
  #     tls:
  #       cluster_issuer: cloudflare-prod
  #       secret: mbelt-karura-polka-p2p-world
  #       ssl_redirect: true
  #
  # - name: acala
  #   image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer_karura, tag: v1.0.0 }
  #   limits: { cpu: 700m, memory: 3Gi }
  #   requests: { cpu: 500m, memory: 3Gi }
  #   port: 3000
  #   db: *db
  #   env:
  #     substrate_uri: ws://acala-node-0.acala-node.acala.svc.cluster.local:9945
  #     log_level: warn
  #     preload: true
  #     subscribe: true
  #     start_block_id: 0
  #   ingress:
  #     enabled: true
  #     class: nginx-external
  #     host: mbelt-acala.polka.p2p.world
  #     tls:
  #       cluster_issuer: cloudflare-prod
  #       secret: mbelt-acala-polka-p2p-world
  #       ssl_redirect: true
  #
  # - name: shiden
  #   image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer_shiden, tag: v1.0.0 }
  #   limits: { cpu: 700m, memory: 3Gi }
  #   requests: { cpu: 500m, memory: 3Gi }
  #   port: 3000
  #   db: *db
  #   env:
  #     substrate_uri: ws://shiden-node-0.shiden-node.shiden.svc.cluster.local:9945
  #     log_level: warn
  #     preload: true
  #     subscribe: true
  #     start_block_id: 0
  #   ingress:
  #     enabled: true
  #     class: nginx-external
  #     host: mbelt-shiden.polka.p2p.world
  #     tls:
  #       cluster_issuer: cloudflare-prod
  #       secret: mbelt-shiden-polka-p2p-world
  #       ssl_redirect: true
