---
environment: prod
name: polkadot
image: {repository: eu.gcr.io/substrate-infra/mbelt2_streamer, tag: 9707a94329e7c4abb20811242db280dcb19bc0bb}
limits: {cpu: 1000m, memory: 2Gi}
requests: {cpu: 300m, memory: 2Gi}
port: 3000
metrics:
  enabled: true
vault:
  role: "mbelt"
  secret: "secret/mbelt/v2_prod"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: trace
  preload: true
  subscribe: true
  start_block_id: 0
  network: polkadot
ingress:
  enabled: true
  class: nginx-external
  host: mbelt-polkadot.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt-polkadot-polka-p2p-world
    ssl_redirect: true
