---
environment: stage
replicas: 70
name: block-processor
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: 5ec3d6c98c36cf8af47ec809b68428acfe24b5ee}
limits: {cpu: 450m, memory: 512Mi}
requests: {cpu: 350m, memory: 512Mi}
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: BLOCK_PROCESSOR
  network: polkadot
ingress:
  enabled: false
