---
environment: stage
name: preloader
replicas: 1
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: 663e9e079f4e38dd74f65f3f1de92ef8fe67b0ff}
limits: {cpu: 450m, memory: 200Mi}
requests: {cpu: 400m, memory: 200Mi}
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: LISTENER
  network: polkadot
ingress:
  enabled: true
  class: nginx-external
  host: mbelt-stage-preloader.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt-stage-preloader-polka-p2p-world
    ssl_redirect: true
