---
environment: stage
name: staking-processor
replicas: 1
limits: {cpu: 450m, memory: 4096Mi}
requests: {cpu: 350m, memory: 4096Mi}
image: {repository: eu.gcr.io/substrate-infra/mbelt3_preloader, tag: b8276a56a0317feb41b83202b51cc18e3ae2e1bc}
port: 3000
metrics:
  enabled: false
vault:
  role: "mbelt"
  secret: "secret/mbelt/stage"
additional_args:
  - "--max_old_space_size=4096"
env:
  substrate_uri: ws://polkadot-node-0.polkadot-node.polkadot.svc.cluster.local:9944
  log_level: info
  network_id: 1
  mode: STAKING_PROCESSOR
  network: polkadot
ingress:
  enabled: true
  class: nginx-external
  host: mbelt-stage-staking-processor.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt-stage-staking-processor-polka-p2p-world
    ssl_redirect: true
