---
environment: prod

chain: polkadot
role: polkadot
image: { repository: eu.gcr.io/substrate-infra/mbelt2_streamer_moonbeam, tag: v1.0.10 }
limits: { cpu: 700m, memory: 2Gi }
requests: { cpu: 500m, memory: 2Gi }
port: 3000

metrics:
  enabled: true

vault:
  role: "mbelt"
  secret: "secret/mbelt/v2_prod"

env:
  substrate_uri: ws://moonriver-node-0.moonriver-node.moonriver.svc.cluster.local:9945
  log_level: warn
  preload: true
  subscribe: true
  start_block_id: 0
  network: moonriver
ingress:
  enabled: true
  class: nginx-external
  host: mbelt-moonriver.polka.p2p.world
  tls:
    cluster_issuer: cloudflare-prod
    secret: mbelt-moonriver-polka-p2p-world
    ssl_redirect: true
