name: Security Testing

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  sast:
    uses: p2p-org/security-workflows/.github/workflows/sast.yaml@e726caf9621e3f06560265a1678e8af43ee1903d # main
    secrets: inherit
  sca:
    uses: p2p-org/security-workflows/.github/workflows/sca.yaml@e726caf9621e3f06560265a1678e8af43ee1903d # main
    secrets: inherit
