name: Security Testing

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  sast:
    uses: p2p-org/security-workflows/.github/workflows/sast.yaml@af967ff16dd0b2a12e96d7f0bb045f5b6827ecc8 # main
    secrets: inherit
  sca:
    uses: p2p-org/security-workflows/.github/workflows/sca.yaml@af967ff16dd0b2a12e96d7f0bb045f5b6827ecc8 # main
    secrets: inherit
